from functools import lru_cache

ALL_LAB_NAMES = [
    "AdaptableSnail",
    "BoisterousParrot",
    "CRIM13",
    "CalMS21_supplemental",
    "CalMS21_task1",
    "CalMS21_task2",
    "CautiousGiraffe",
    "DeliriousFly",
    "ElegantMink",
    "GroovyShrew",
    "InvincibleJellyfish",
    "JovialSwallow",
    "LyricalHare",
    "MABe22_keypoints",
    "MABe22_movies",
    "NiftyGoldfinch",
    "PleasantMeerkat",
    "ReflectiveManatee",
    "SparklingTapir",
    "TranquilPanther",
    "UppityFerret",
]

LAB_NAMES_WITH_ANNOTATION = [
    "AdaptableSnail",
    "BoisterousParrot",
    "CRIM13",
    "CalMS21_supplemental",
    "CalMS21_task1",
    "CalMS21_task2",
    "CautiousGiraffe",
    "DeliriousFly",
    "ElegantMink",
    "GroovyShrew",
    "InvincibleJellyfish",
    "JovialSwallow",
    "LyricalHare",
    "NiftyGoldfinch",
    "PleasantMeerkat",
    "ReflectiveManatee",
    "SparklingTapir",
    "TranquilPanther",
    "UppityFerret",
]

LAB_NAMES_IN_TEST = [
    "AdaptableSnail",
    "BoisterousParrot",
    "CautiousGiraffe",
    "DeliriousFly",
    "ElegantMink",
    "GroovyShrew",
    "InvincibleJellyfish",
    "JovialSwallow",
    "LyricalHare",
    "NiftyGoldfinch",
    "PleasantMeerkat",
    "ReflectiveManatee",
    "SparklingTapir",
    "TranquilPanther",
    "UppityFerret",
]

ALL_ACTION_NAMES = [
    "allogroom",
    "approach",
    "attack",
    "attemptmount",
    "avoid",
    "biteobject",
    "chase",
    "chaseattack",
    "climb",
    "defend",
    "dig",
    "disengage",
    "dominance",
    "dominancegroom",
    "dominancemount",
    "escape",
    "exploreobject",
    "flinch",
    "follow",
    "freeze",
    "genitalgroom",
    "huddle",
    "intromit",
    "mount",
    "rear",
    "reciprocalsniff",
    "rest",
    "run",
    "selfgroom",
    "shepherd",
    "sniff",
    "sniffbody",
    "sniffface",
    "sniffgenital",
    "submit",
    "tussle",
]

ACTIONS_TO_REMOVE = ["ejaculate"]

ACTION_NAMES_IN_TEST = [
    "allogroom",
    "approach",
    "attack",
    "attemptmount",
    "avoid",
    "biteobject",
    "chase",
    "chaseattack",
    "climb",
    "defend",
    "dig",
    "dominance",
    "dominancegroom",
    "escape",
    "exploreobject",
    "flinch",
    "follow",
    "freeze",
    "huddle",
    "intromit",
    "mount",
    "rear",
    "reciprocalsniff",
    "rest",
    "run",
    "selfgroom",
    "shepherd",
    "sniff",
    "sniffbody",
    "sniffface",
    "sniffgenital",
    "submit",
    "tussle",
]

ALL_PAIR_ACTIONS = [
    "allogroom",
    "approach",
    "attack",
    "attemptmount",
    "avoid",
    "chase",
    "chaseattack",
    "defend",
    "disengage",
    "dominance",
    "dominancegroom",
    "dominancemount",
    "escape",
    "flinch",
    "follow",
    "intromit",
    "mount",
    "reciprocalsniff",
    "shepherd",
    "sniff",
    "sniffbody",
    "sniffface",
    "sniffgenital",
    "submit",
    "tussle",
]

ALL_SELF_ACTIONS = [
    "biteobject",
    "climb",
    "dig",
    "exploreobject",
    "freeze",
    "genitalgroom",
    "huddle",
    "rear",
    "rest",
    "run",
    "selfgroom",
]


ALL_BODYPART_NAMES = [
    "body_center",
    "ear_left",
    "ear_right",
    "forepaw_left",
    "forepaw_right",
    "head",
    "headpiece_bottombackleft",
    "headpiece_bottombackright",
    "headpiece_bottomfrontleft",
    "headpiece_bottomfrontright",
    "headpiece_topbackleft",
    "headpiece_topbackright",
    "headpiece_topfrontleft",
    "headpiece_topfrontright",
    "hindpaw_left",
    "hindpaw_right",
    "hip_left",
    "hip_right",
    "lateral_left",
    "lateral_right",
    "neck",
    "nose",
    "spine_1",
    "spine_2",
    "tail_base",
    "tail_middle_1",
    "tail_middle_2",
    "tail_midpoint",
    "tail_tip",
]

SYMMETRIC_BODYPART_PAIRS = [
    ("ear_left", "ear_right"),
    ("forepaw_left", "forepaw_right"),
    ("headpiece_bottombackleft", "headpiece_bottombackright"),
    ("headpiece_bottomfrontleft", "headpiece_bottomfrontright"),
    ("headpiece_topbackleft", "headpiece_topbackright"),
    ("headpiece_topfrontleft", "headpiece_topfrontright"),
    ("hindpaw_left", "hindpaw_right"),
    ("hip_left", "hip_right"),
    ("lateral_left", "lateral_right"),
]


@lru_cache
def get_opposite_bodypart(name: str) -> str:
    for left, right in SYMMETRIC_BODYPART_PAIRS:
        if left == name:
            return right
        if right == name:
            return left
    return name


MOUSE_CATEGORICAL_FEATURES = {
    "strain": [
        "129/SvEvTac",
        "BALB/c",
        "BTBR",
        "C57Bl/6J",
        "C57Bl/6J x Ai148",
        "C57Bl/6N",
        "CD-1 (ICR)",
        "CD1",
        "CFW",
        None,
    ],
    "color": ["black", "black and tan", "brown", "white", None],
    "sex": ["female", "male", None],
    "age": [
        "10-20 weeks",
        "12 weeks",
        "17-21 weeks",
        "4-6 weeks",
        "6-12 weeks",
        "7-14 weeks",
        "8 weeks",
        "8-12 weeks",
        "8-13 weeks",
        "8-26 weeks",
        "8-57 weeks",
        "> 40 weeks",
        None,
    ],
    "condition": [
        "cable",
        "cabled device",
        "castrated",
        "csds",
        "dam",
        "estrus",
        "hormone primed",
        "lights off",
        "lights on",
        "mated",
        "naive",
        "ovariectomized",
        "social isolation",
        "stress",
        "wireless device",
        None,
    ],
}

VIDEO_CATEGORICAL_FEATURES = {
    "lab_id": [
        "AdaptableSnail",
        "BoisterousParrot",
        "CRIM13",
        "CalMS21_supplemental",
        "CalMS21_task1",
        "CalMS21_task2",
        "CautiousGiraffe",
        "DeliriousFly",
        "ElegantMink",
        "GroovyShrew",
        "InvincibleJellyfish",
        "JovialSwallow",
        "LyricalHare",
        "MABe22_keypoints",
        "MABe22_movies",
        "NiftyGoldfinch",
        "PleasantMeerkat",
        "ReflectiveManatee",
        "SparklingTapir",
        "TranquilPanther",
        "UppityFerret",
    ],
    "arena_shape": ["circular", "rectangular", "split rectangluar", "square"],
    "arena_type": [
        None,
        "CSDS",
        "divided territories",
        "familiar",
        "neutral",
        "resident-intruder",
    ],
    "tracking_method": ["DeepLabCut", "MARS", "SLEAP", "custom HRnet"],
}

LABS_IN_TEST_PER_ACTION = {
    "allogroom": ["ElegantMink", "InvincibleJellyfish"],
    "approach": ["AdaptableSnail", "GroovyShrew", "LyricalHare", "NiftyGoldfinch"],
    "attack": [
        "AdaptableSnail",
        "DeliriousFly",
        "ElegantMink",
        "InvincibleJellyfish",
        "JovialSwallow",
        "LyricalHare",
        "NiftyGoldfinch",
        "PleasantMeerkat",
        "ReflectiveManatee",
        "SparklingTapir",
    ],
    "attemptmount": ["ElegantMink", "GroovyShrew"],
    "avoid": ["AdaptableSnail"],
    "biteobject": ["NiftyGoldfinch"],
    "chase": [
        "AdaptableSnail",
        "CautiousGiraffe",
        "JovialSwallow",
        "NiftyGoldfinch",
        "PleasantMeerkat",
    ],
    "chaseattack": ["AdaptableSnail"],
    "climb": ["GroovyShrew", "NiftyGoldfinch"],
    "defend": ["GroovyShrew", "LyricalHare", "NiftyGoldfinch", "SparklingTapir"],
    "dig": ["GroovyShrew", "InvincibleJellyfish", "NiftyGoldfinch"],
    "dominance": ["DeliriousFly"],
    "dominancegroom": ["InvincibleJellyfish"],
    "escape": [
        "CautiousGiraffe",
        "GroovyShrew",
        "InvincibleJellyfish",
        "LyricalHare",
        "NiftyGoldfinch",
        "PleasantMeerkat",
        "SparklingTapir",
    ],
    "exploreobject": ["NiftyGoldfinch"],
    "flinch": ["NiftyGoldfinch"],
    "follow": ["NiftyGoldfinch", "PleasantMeerkat"],
    "freeze": ["LyricalHare"],
    "huddle": ["UppityFerret"],
    "intromit": ["ElegantMink", "TranquilPanther"],
    "mount": ["ElegantMink", "SparklingTapir", "TranquilPanther"],
    "rear": [
        "AdaptableSnail",
        "GroovyShrew",
        "LyricalHare",
        "NiftyGoldfinch",
        "TranquilPanther",
    ],
    "reciprocalsniff": ["CautiousGiraffe", "UppityFerret"],
    "rest": ["GroovyShrew"],
    "run": ["GroovyShrew"],
    "selfgroom": [
        "GroovyShrew",
        "InvincibleJellyfish",
        "NiftyGoldfinch",
        "TranquilPanther",
    ],
    "shepherd": ["BoisterousParrot"],
    "sniff": [
        "CautiousGiraffe",
        "DeliriousFly",
        "ElegantMink",
        "GroovyShrew",
        "InvincibleJellyfish",
        "JovialSwallow",
        "LyricalHare",
        "NiftyGoldfinch",
        "ReflectiveManatee",
        "TranquilPanther",
    ],
    "sniffbody": ["CautiousGiraffe"],
    "sniffface": ["NiftyGoldfinch"],
    "sniffgenital": [
        "CautiousGiraffe",
        "GroovyShrew",
        "InvincibleJellyfish",
        "NiftyGoldfinch",
        "TranquilPanther",
        "UppityFerret",
    ],
    "submit": ["AdaptableSnail"],
    "tussle": ["NiftyGoldfinch"],
}

DEFAULT_DURATION_CAP = 1e6 / 30 + 6

ACTIONS_PER_ENSEMBLE_APPROACH = {
    '{\n    "max_models": 3,\n    "filter_same_model_type": false,\n    "objective": "nested_f1",\n    "num_weight_bins": 10,\n    "pool_size": 1,\n    "refit_with_fold_avg": false,\n    "avg_k_best": false,\n    "logreg": false\n}': [
        "allogroom",
        "attemptmount",
        "approach",
        "chase",
        "chaseattack",
        "climb",
        "defend",
        "dominance",
        "dominancegroom",
        "exploreobject",
        "escape",
        "freeze",
        "huddle",
        "intromit",
        "mount",
        "rear",
        "rest",
        "selfgroom",
        "sniffbody",
        "submit",
    ],
    '{\n    "max_models": 3,\n    "filter_same_model_type": false,\n    "objective": "logloss",\n    "num_weight_bins": 10,\n    "pool_size": 1,\n    "refit_with_fold_avg": false,\n    "avg_k_best": false,\n    "logreg": false\n}': [
        "avoid",
        "attack",
        "biteobject",
        "dig",
        "flinch",
        "follow",
        "reciprocalsniff",
        "run",
        "shepherd",
        "sniff",
        "sniffface",
        "sniffgenital",
    ],
}

BODYPART_GROUPS_V0 = {
    "head": [
        "nose",
        "head",
        "neck",
        "ear_left",
        "ear_right",
        "headpiece_bottombackleft",
        "headpiece_bottombackright",
        "headpiece_bottomfrontleft",
        "headpiece_bottomfrontright",
        "headpiece_topbackleft",
        "headpiece_topbackright",
        "headpiece_topfrontleft",
        "headpiece_topfrontright",
    ],
    "front_paws": [
        "forepaw_left",
        "forepaw_right",
    ],
    "hind_paws": [
        "hindpaw_left",
        "hindpaw_right",
    ],
    "torso": [
        "body_center",
        "spine_1",
        "spine_2",
        "lateral_left",
        "lateral_right",
        "hip_left",
        "hip_right",
    ],
    "tail": [
        "tail_base",
        "tail_middle_1",
        "tail_middle_2",
        "tail_midpoint",
        "tail_tip",
    ],
}

BODYPART_GROUPS_V1 = {
    # head & neck
    "head_midline": [
        "nose",
        "head",
        "neck",
    ],
    "head_left": [
        "ear_left",
        "headpiece_bottombackleft",
        "headpiece_bottomfrontleft",
        "headpiece_topbackleft",
        "headpiece_topfrontleft",
    ],
    "head_right": [
        "ear_right",
        "headpiece_bottombackright",
        "headpiece_bottomfrontright",
        "headpiece_topbackright",
        "headpiece_topfrontright",
    ],
    # paws – separate group per paw
    "forepaw_left": [
        "forepaw_left",
    ],
    "forepaw_right": [
        "forepaw_right",
    ],
    "hindpaw_left": [
        "hindpaw_left",
    ],
    "hindpaw_right": [
        "hindpaw_right",
    ],
    # torso & near-torso
    "torso_midline": [
        "body_center",
        "spine_1",
        "spine_2",
    ],
    "torso_left": [
        "hip_left",
        "lateral_left",
    ],
    "torso_right": [
        "hip_right",
        "lateral_right",
    ],
    # tail as one block
    "tail": [
        "tail_base",
        "tail_middle_1",
        "tail_middle_2",
        "tail_midpoint",
        "tail_tip",
    ],
}

BODYPART_GROUPS_V2 = {
    # central head / body core
    "nose_only": [
        "nose",
    ],
    "head_core": [
        "head",
        "neck",
        "body_center",
    ],
    # ears as one group
    "ears": [
        "ear_left",
        "ear_right",
    ],
    # headpiece split into front / back
    "headpiece_front": [
        "headpiece_bottomfrontleft",
        "headpiece_bottomfrontright",
        "headpiece_topfrontleft",
        "headpiece_topfrontright",
    ],
    "headpiece_back": [
        "headpiece_bottombackleft",
        "headpiece_bottombackright",
        "headpiece_topbackleft",
        "headpiece_topbackright",
    ],
    # paws
    "forepaws": [
        "forepaw_left",
        "forepaw_right",
    ],
    "hindpaws": [
        "hindpaw_left",
        "hindpaw_right",
    ],
    # torso bits
    "hips": [
        "hip_left",
        "hip_right",
    ],
    "laterals": [
        "lateral_left",
        "lateral_right",
    ],
    "spine": [
        "spine_1",
        "spine_2",
    ],
    # tail split into base / mid / tip
    "tail_base": [
        "tail_base",
    ],
    "tail_mid": [
        "tail_middle_1",
        "tail_middle_2",
        "tail_midpoint",
    ],
    "tail_tip": [
        "tail_tip",
    ],
}

BODYPART_GROUPS_V3 = {
    "body_center": ["body_center"],
    "ear_left": ["ear_left"],
    "ear_right": ["ear_right"],
    "forepaw_left": ["forepaw_left"],
    "forepaw_right": ["forepaw_right"],
    "head": ["head"],
    "headpiece_bottombackleft": ["headpiece_bottombackleft"],
    "headpiece_bottombackright": ["headpiece_bottombackright"],
    "headpiece_bottomfrontleft": ["headpiece_bottomfrontleft"],
    "headpiece_bottomfrontright": ["headpiece_bottomfrontright"],
    "headpiece_topbackleft": ["headpiece_topbackleft"],
    "headpiece_topbackright": ["headpiece_topbackright"],
    "headpiece_topfrontleft": ["headpiece_topfrontleft"],
    "headpiece_topfrontright": ["headpiece_topfrontright"],
    "hindpaw_left": ["hindpaw_left"],
    "hindpaw_right": ["hindpaw_right"],
    "hip_left": ["hip_left"],
    "hip_right": ["hip_right"],
    "lateral_left": ["lateral_left"],
    "lateral_right": ["lateral_right"],
    "neck": ["neck"],
    "nose": ["nose"],
    "spine_1": ["spine_1"],
    "spine_2": ["spine_2"],
    "tail_base": ["tail_base"],
    "tail_middle_1": ["tail_middle_1"],
    "tail_middle_2": ["tail_middle_2"],
    "tail_midpoint": ["tail_midpoint"],
    "tail_tip": ["tail_tip"],
}

REMOVE_25_FPS_ADAP_SNAIL_SUFFIX = "-remove-25fps-adap-snail"
